#!/bin/sh

cd $(dirname $0)/..

REMOTE_BOX_VERSION=$(vagrant cloud search --provider virtualbox --json "ubuntu/bionic64" | jq '.[] | select(.name == "ubuntu/bionic64") | .version' | tr -d '"')

if grep -q "${REMOTE_BOX_VERSION}" box_version; then
  echo "No new version released by upstream"
else
  echo "Found new upstream version: ${REMOTE_BOX_VERSION}"
  if [ -z ${DRY_RUN+x} ];then
    REPO=${GITHUB_REPOSITORY:-"leodotcloud/vagrant-box-bionic64"}
    INPUT_BRANCH=main
    ACTOR=${GITHUB_ACTOR:-leodotcloud}
    REMOTE="https://${ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

    echo "${REMOTE_BOX_VERSION}" >| box_version
    git add box_version
    git commit -m "bumping box version to ${REMOTE_BOX_VERSION}"
    git tag "${REMOTE_BOX_VERSION}"
    git push "${REMOTE}" HEAD:${INPUT_BRANCH} --follow-tags --tags
  else
    echo "dry run, no action taken"
  fi
fi